v1.3.7 * 添加 -viper 安装选项 * -k 选项添加 pocsuite3 工具 * 添加一个 pip3_Check 函数单独判断 pip3 命令是否存在,不存在自动调用 Python3_Install 函数进行安装 * 安装开发环境依赖时,debian 系安装 libcurl4-openssl-dev * 修复安装 Impacket 时的一个错误

diff --git a/f8x b/f8x
--- a/f8x
+++ b/f8x
@@ -25,7 +25,7 @@ Default_DNS=223.5.5.5
 Proxy_URL=https://ffffffff0x.com/proxychains-ng.zip
 Porxy_OK=
 error=0
-F8x_Version="1.3.6 Dev"
+F8x_Version="1.3.7 Dev"
 
 # ===================== 软件版本变量设置 =====================
 jdk_Version=jdk1.8.0_271
@@ -135,6 +135,19 @@ Dev_Check(){
         echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m开发环境正常\033[0m"
     fi
 
+}
+
+pip3_Check(){
+
+    pip3 -V 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32mpip3 可用\033[0m" && error=0 || error=1
+
+    if [ $error == 1 ]
+    then
+        echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m依赖项不通过,即将自动安装 pip3\033[0m"
+        Python3_Install
+    else
+        echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m依赖项正常\033[0m"
+    fi
 }
 
 # ===================== 代理开关 =====================
@@ -892,7 +905,8 @@ Dev_Base_Install(){
             yum groupinstall -y "Development Tools" 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已安装 Development Tools\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m安装 Development Tools 失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
             ;;
         *)
-            echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m环境正常\033[0m"
+            Rm_Lock
+            apt-get install -y libcurl4-openssl-dev 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已安装 libcurl4-openssl-dev 工具\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m安装 libcurl4-openssl-dev 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
             ;;
     esac
 
@@ -1034,6 +1048,7 @@ Docker_Install(){
     then
         echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;33m[ALERT]\033[0m - \033[1;33mdocker-compose 已安装\033[0m"
     else
+        pip3_Check
         pip3 install docker-compose 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已安装 docker-compose\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m安装 docker-compose 失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
     fi
 
@@ -1279,7 +1294,8 @@ Pentest_Impacket_Install(){
 
     rm -rf $P_Dir/impacket 1> /dev/null 2>> /tmp/f8x_error.log && $Porxy_OK git clone https://github.com/SecureAuthCorp/impacket.git $P_Dir/impacket 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已下载 impacket 工具\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31mimpacket 工具下载失败! 请检查 proxychains4 配置的代理服务器是否可用! \n\033[0m"
     cd $P_Dir/impacket
-    pip3 install . 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已安装 Impacket 在 $P_Dir/impacket 目录下\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m安装 Impacket 工具失败!\033[0m"
+    pip3 install . 1> /dev/null 2>> /tmp/f8x_error.log
+    python3 setup.py install 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已安装 Impacket 在 $P_Dir/impacket 目录下\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m安装 Impacket 工具失败!\033[0m"
 
 }
 
@@ -1396,6 +1412,13 @@ Pentest_fscan_Install(){
 
 }
 
+# ===================== 安装 pocsuite3 工具 =====================
+Pentest_pocsuite3_Install(){
+
+    pip3 install pocsuite3 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已安装 pocsuite3 工具,直接输入 pocsuite 即可使用\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m安装 pocsuite3 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
+
+}
+
 # ===================== 安装 unyaffs 工具 =====================
 unyaffs_Install(){
 
@@ -1481,15 +1504,7 @@ AdguardTeam_Install(){
 # ===================== 安装 trash-cli 环境 =====================
 trash-cli_Install(){
 
-    pip3 -V 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32mpip3 可用\033[0m" && error=0 || error=1
-
-    if [ $error == 1 ]
-    then
-        echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m依赖项不通过,即将自动安装 pip3\033[0m"
-        Python3_Install
-    else
-        echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m依赖项正常\033[0m"
-    fi
+    pip3_Check
 
     pip3 install trash-cli 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已安装 trash-cli 环境,现在可使用以下命令进行管理:\n- 移动文件到回收站 : trash-put\n- 列出回收站文件 : trash-list\n- 搜索回收站文件 : trash-list | grep foo\n- 恢复回收站文件 : trash-restore\n- 删除所有回收站文件 : trash-empty\n- 删除回收站中 n 天前被回收的文件 : trash-empty <days>\n- 只删除符合某种模式的文件 : trash-rm \\\*.o\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m安装 trash-cli 环境失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
 
@@ -1878,6 +1893,49 @@ awvs13_Install(){
 
 }
 
+# -viper
+viper_Install(){
+
+    echo -e "\033[1;33m\n>> 正在检测 Docker 可用性\n\033[0m"
+    Docker_Install
+
+    echo -e "\033[1;33m\n>> 正在部署 Viper 环境\033[0m"
+
+    mkdir -p /tmp/viper
+    cd /tmp/viper
+    rm -rf docker-compose.* 1> /dev/null 2>> /tmp/f8x_error.log
+
+    viper_conf 1> /dev/null 2>> /tmp/f8x_error.log
+
+    echo -e "\033[5;33m\n请输入 Viper 密码\033[0m" && read -r input
+    Viper_Pass=$input
+    cat docker-compose.yml.bak | sed "s/diypassword/$Viper_Pass/" >> docker-compose.yml
+    docker-compose up -d
+
+    echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m等待系统启动(15s),访问 https://vpsip:60000 登录服务器. 用户名:root 密码:$Viper_Pass \033[0m"
+
+}
+
+viper_conf(){
+
+tee docker-compose.yml.bak <<-'EOF'
+version: "3"
+services:
+  viper:
+    image: registry.cn-shenzhen.aliyuncs.com/toys/viper:latest
+    container_name: viper-c
+    network_mode: "host"
+    restart: always
+    volumes:
+      - /root/viper/loot:/root/.msf4/loot
+      - /root/viper/db:/root/viper/Docker/db
+      - /root/viper/module:/root/viper/Docker/module
+      - /root/viper/log:/root/viper/Docker/log
+    command: ["diypassword"]
+EOF
+
+}
+
 # -arl
 arl_Install(){
 
@@ -2250,6 +2308,8 @@ kali_Tools(){
     Pentest_masscan_Install
     echo -e "\033[1;33m\n>> 正在安装 fscan 工具\n\033[0m"
     Pentest_fscan_Install
+    echo -e "\033[1;33m\n>> 正在安装 pocsuite3 工具\n\033[0m"
+    Pentest_pocsuite3_Install
 
 }
 
@@ -2311,6 +2371,7 @@ Help(){
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-cs\033[0m \033[0;34m选项部署 CobaltStrike 环境 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-goby\033[0m \033[0;34m选项部署 Goby 环境 (需要图形化环境)\033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-awvs13\033[0m \033[0;34m选项部署 AWVS13 环境\033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-viper\033[0m \033[0;34m选项部署 Viper 环境 (本项不稳定)\033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-arl\033[0m \033[0;34m选项部署 ARL 环境\033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-frp\033[0m \033[0;34m选项部署 frp 环境 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-nps\033[0m \033[0;34m选项部署 nps 环境 \033[0m"
@@ -2486,6 +2547,10 @@ case "$1" in
     -awvs13)
         Porxy_Switch
         awvs13_Install
+        ;;
+    -viper)
+        Porxy_Switch
+        viper_Install
         ;;
     -arl)
         Pentest_Base_Install
