1.4.6

diff --git a/f8x b/f8x
--- a/f8x
+++ b/f8x
@@ -25,7 +25,7 @@ Proxy_URL="https://cdn.ffffffff0x.com/?durl=https://codeload.github.com/rofl0r/p
 Porxy_OK=
 Docker_OK=
 error=0
-F8x_Version="1.4.5 Dev"
+F8x_Version="1.4.6 Dev"
 
 # ===================== 软件版本变量设置 =====================
 jdk_Version=jdk1.8.0_271
@@ -451,7 +451,7 @@ Info(){
 
     esac
 
-    echo -e "\033[1;32mf8x版本 :\033[0m \033[1;35m$F8x_Version \033[0m"
+    echo -e "\033[1;32m当前版本 :\033[0m \033[1;35m$F8x_Version \033[0m"
 }
 
 # ===================== 修改 apt 源 =====================
@@ -1230,6 +1230,15 @@ Docker_Install(){
 
 }
 
+# ===================== 安装 SDKMAN =====================
+SDKMAN_Install(){
+
+    cd /tmp && $Porxy_OK curl -o sdkman.sh "https://get.sdkman.io" > /dev/null 2>&1 && $Porxy_OK bash sdkman.sh > /dev/null 2>&1
+    source "/root/.sdkman/bin/sdkman-init.sh"
+    sdk version && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已安装 SDKMAN 工具\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m安装 SDKMAN 工具失败\n\033[0m"
+
+}
+
 # ===================== 安装 Terraform =====================
 Terraform_Install(){
 
@@ -1240,9 +1249,7 @@ Terraform_Install(){
         echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;33m[ALERT]\033[0m - \033[1;33m正在下载 terraform 安装包"
         cd /tmp && $Porxy_OK wget https://releases.hashicorp.com/terraform/$Terraform_Ver/$Terraform_bin > /dev/null 2>&1 && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已从 hashicorp.com 下载完安装包\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m下载 Terraform 安装包失败! 请检查 proxychains4 配置的代理服务器是否可用!  \n\033[0m"
         unzip $Terraform_bin > /dev/null 2>&1
-        mv terraform /usr/local/bin/terraform 1> /dev/null 2>> /tmp/f8x_error.log
-
-        echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已安装 terraform $Terraform_Ver 工具,输入 terraform 即可使用\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31mTerraform 安装失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
+        mv terraform /usr/local/bin/terraform 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已安装 terraform $Terraform_Ver 工具,输入 terraform 即可使用\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31mTerraform 安装失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
     fi
 
 }
@@ -2028,6 +2035,28 @@ binwalk_force_Install(){
 
 }
 
+# -clamav
+clamav_Install(){
+
+    echo -e "\033[1;33m\n>> 正在安装 clamav\n\033[0m"
+
+    Rm_Lock
+    case $Linux_Version in
+        *"CentOS"*|*"RedHat"*|*"Fedora"*)
+            yum install -y clamav 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已安装 clamav 工具\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m安装 clamav 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
+            yum install -y clamav-update 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已安装 clamav-update 工具\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m安装 clamav-update 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
+            $Porxy_OK freshclam
+            ;;
+        *"Kali"*|*"Ubuntu"*|*"Debian"*)
+            apt-get install -y clamav 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已安装 clamav 工具\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m安装 clamav 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
+            systemctl stop clamav-freshclam.service
+            $Porxy_OK freshclam -v
+            ;;
+        *) ;;
+    esac
+
+}
+
 # -python2
 Python2_Install(){
 
@@ -2064,7 +2093,7 @@ Python2_Install(){
 pip2_Install(){
 
     echo -e "\033[1;33m\n>> 正在安装 pip2\n\033[0m"
-    cd $T_Dir && $Porxy_OK curl https://bootstrap.pypa.io/2.7/get-pip.py --output get-pip.py 1> /dev/null 2>> /tmp/f8x_error.log || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m https://bootstrap.pypa.io/get-pip.py 下载失败! 请检查 proxychains4 配置的代理服务器是否可用! \n\033[0m"
+    cd $T_Dir && $Porxy_OK curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py 1> /dev/null 2>> /tmp/f8x_error.log || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m https://bootstrap.pypa.io/get-pip.py 下载失败! 请检查 proxychains4 配置的代理服务器是否可用! \n\033[0m"
     $Porxy_OK python2 get-pip.py 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已安装 python-pip 工具\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m安装 python-pip 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
     rm -rf get-pip.py 1> /dev/null 2>> /tmp/f8x_error.log
     python2 -m pip install setuptools > /dev/null 2>&1 && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已安装 setuptools 模块\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m安装 setuptools 模块失败! 请尝试更换 pip 代理或检查 python2 是否已安装! \n\033[0m"
@@ -2443,7 +2472,7 @@ cs_Install(){
 
     Pentest_Base_Install
 
-    echo -e "\033[1;33m\n>> 正在部署 CobaltStrike 环境\n\033[0m"
+    echo -e "\033[1;33m\n>> 正在部署 CobaltStrike 4.1 环境\n\033[0m"
     Pentest_CobaltStrike_Install
     echo -e "\033[5;33m\n请输入你的 teamserver 服务端 IP\033[0m" && read -r input
     CS_IP=$input
@@ -2492,6 +2521,7 @@ suricata_Install(){
             exit 1
             ;;
         *"Kali"*|*"Ubuntu"*|*"Debian"*)
+            Rm_Lock
             add-apt-repository ppa:oisf/suricata-stable
             apt-get install -y jq 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已安装 jq 工具\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m安装 jq 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
             apt-get install -y suricata 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已安装 suricata 工具\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m安装 suricata 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
@@ -2507,7 +2537,7 @@ suricata_Install(){
 ssr_Install(){
 
     echo -e "\033[1;33m\n>> 正在部署 ssr 工具\n\033[0m"
-    cd $T_Dir && rm -rf shadowsocksr* 1> /dev/null 2>> /tmp/f8x_error.log && $Porxy_OK wget https://gitee.com/asdasdasd123123/temp613123/raw/master/ssr.zip 1> /dev/null 2>> /tmp/f8x_error.log
+    cd $T_Dir && rm -rf shadowsocksr* 1> /dev/null 2>> /tmp/f8x_error.log && wget https://cdn.jsdelivr.net/gh/No-Github/Archive@1.0.3/ssr/ssr.zip 1> /dev/null 2>> /tmp/f8x_error.log
     unzip -P 123456 ssr.zip 1> /dev/null 2>> /tmp/f8x_error.log && rm -rf ssr.zip 1> /dev/null 2>> /tmp/f8x_error.log
     cd shadowsocksr && bash initcfg.sh && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已部署 ssr 工具\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m部署 ssr 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
     echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;33m运行下列命令修改 ssr 配置:\n\033[0m\033[1;32mvim $T_Dir/shadowsocksr/user-config.json\n\033[0m"
@@ -2740,6 +2770,8 @@ Dev_Tools(){
     Go_Install
     echo -e "\033[1;33m\n>> 正在安装 Docker 和 Docker-compose\n\033[0m"
     Docker_Install
+    echo -e "\033[1;33m\n>> 正在安装 SDKMAN!\n\033[0m"
+    SDKMAN_Install
 
 }
 
@@ -2885,7 +2917,7 @@ Help(){
     echo -e "\033[1;34m1. 批量化安装 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-b\033[0m \033[0;34m选项安装基本环境 \033[0m       \033[1;32m(gcc、make、git、vim、telnet、jq、unzip 等基本工具)\033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-p\033[0m \033[0;34m选项安装代理环境 \033[0m       \033[1;31m(警告:国外云服务器上不要用,会降速)\033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-d\033[0m \033[0;34m选项安装开发环境 \033[0m       \033[1;32m(python3、pip3、Go、Docker、Docker-Compose)\033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-d\033[0m \033[0;34m选项安装开发环境 \033[0m       \033[1;32m(python3、pip3、Go、Docker、Docker-Compose、SDKMAN)\033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-k\033[0m \033[0;34m选项安装渗透环境 \033[0m       \033[1;32m(hashcat、ffuf、OneForAll、ksubdomain、impacket 等渗透工具)\033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-s\033[0m \033[0;34m选项安装蓝队环境 \033[0m       \033[1;32m(Fail2Ban、chkrootkit、rkhunter、河马webshell查杀工具)\033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-f\033[0m \033[0;34m选项安装其他工具 \033[0m       \033[1;32m(Bash_Insulter、vlmcsd、AdguardTeam、trash-cli)\033[0m"
@@ -2908,7 +2940,7 @@ Help(){
     echo -e "\033[1;34m3. 蓝队服务 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-binwalk\033[0m \033[0;34m选项安装 binwalk 环境 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-binwalk-f\033[0m \033[0;34m选项强制安装 binwalk 环境 \033[0m   \033[1;33m(建议在 -binwalk 选项失败的情况下运行)\033[0m"
-    #echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-clamav\033[0m \033[0;34m选项安装 ClamAV 工具 \033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-clamav\033[0m \033[0;34m选项安装 ClamAV 工具 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-hfish\033[0m \033[0;34m选项安装 HFish 蜜罐 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-lt\033[0m \033[0;34m选项部署 LogonTracer 环境 \033[0m          \033[1;33m(非超高配置机器不要部署,这个应用太吃配置了)\033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-suricata\033[0m \033[0;34m选项部署 Suricata 环境 \033[0m"
@@ -2917,7 +2949,7 @@ Help(){
     echo -e ""
     echo -e "\033[1;34m4. 红队服务 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-bypass\033[0m \033[0;34m选项部署 Bypass 环境 \033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-cs\033[0m \033[0;34m选项部署 CobaltStrike 环境 \033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-cs\033[0m \033[0;34m选项部署 CobaltStrike 4.1 环境 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-frp\033[0m \033[0;34m选项部署 frp 环境 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-goby\033[0m \033[0;34m选项部署 Goby 环境 \033[0m               \033[1;33m(需要图形化环境)\033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-nps\033[0m \033[0;34m选项部署 nps 环境 \033[0m"
@@ -2946,6 +2978,7 @@ Help(){
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-remove\033[0m \033[0;34m选项卸载国内 vps 云监控 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-rmlock\033[0m \033[0;34m选项运行除锁模块 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-swap\033[0m \033[0;34m选项配置 swap 分区 \033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-update\033[0m \033[0;34m选项更新 f8x 工具 \033[0m"
     echo -e ""
     echo -e "\033[1;37m脚本作者 r0fus0d \033[0m"
     echo -e "\033[1;37m|- 感谢 the-fog 在开发过程中对我的折磨 \033[0m"
@@ -3104,11 +3137,11 @@ case "$1" in
         Porxy_Switch
         binwalk_force_Install
         ;;
-    #-clamav)
-    #    Base_Check
-    #    Porxy_Switch
-    #    clamav_Install
-    #    ;;
+    -clamav)
+        Base_Check
+        Porxy_Switch
+        clamav_Install
+        ;;
     -vol)
         Base_Check
         Porxy_Switch
@@ -3228,9 +3261,20 @@ case "$1" in
         ;;
     -rmlock)
         Rm_Lock
+
+        case $Linux_Version in
+            *"Kali"*|*"Ubuntu"*|*"Debian"*)
+                dpkg --configure -a > /dev/null 2>&1
+                ;;
+            *) ;;
+        esac
+
         ;;
     -swap)
         swap_setting
+        ;;
+    -update)
+        curl -o f8x https://cdn.jsdelivr.net/gh/ffffffff0x/f8x@main/f8x > /dev/null 2>&1 && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m更新成功\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m更新失败\n\033[0m"
         ;;
     -debug)
         #Base_Check
