v1.3.2 * 删除 - b 中的一个重复安装 * 修复代理开关中的逻辑错误 * 添加 setuptools 模块的安装 * python2 默认继承到 -d 选项中 * -asciinema 选项添加判断, 用于通过 CI 检测

diff --git a/f8x b/f8x
--- a/f8x
+++ b/f8x
@@ -25,7 +25,7 @@ Default_DNS=223.5.5.5
 Proxy_URL=https://ffffffff0x.com/proxychains-ng.zip
 Porxy_OK=
 error=0
-F8x_Version="1.3.1 Dev"
+F8x_Version="1.3.2 Dev"
 
 # ===================== 软件版本变量设置 =====================
 jdk_Version=jdk1.8.0_271
@@ -134,7 +134,7 @@ Dev_Check(){
 # ===================== 代理开关 =====================
 Porxy_Switch(){
 
-    if [ $($IS_CI)==1 ]
+    if test -e /tmp/IS_CI
     then
         echo -e "\033[1;32mIS_CI\033[0m"
     else
@@ -866,7 +866,6 @@ Base_Tools(){
             apt-get install -y openssl 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 openssl 工具\033[0m" || echo -e "\033[1;31m安装 openssl 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
             apt-get install -y libssl-dev 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 libssl-dev 工具\033[0m" || echo -e "\033[1;31m安装 libssl-dev 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
             apt-get install -y libssh2-1-dev 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 libssh2-1-dev 工具\033[0m" || echo -e "\033[1;31m安装 libssh2-1-dev 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
-            apt-get install -y iftop 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 iftop 工具\033[0m" || echo -e "\033[1;31m安装 iftop 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
             apt-get install -y nethogs 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 nethogs 工具\033[0m" || echo -e "\033[1;31m安装 nethogs 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
             apt-get install -y iptraf 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 iptraf 工具\033[0m" || echo -e "\033[1;31m安装 iptraf 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
             apt-get install -y tcpdump 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 tcpdump 工具\033[0m" || echo -e "\033[1;31m安装 tcpdump 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
@@ -906,6 +905,7 @@ Python3_Install(){
             yum install -y python3-devel 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 python3-devel 工具\033[0m" || echo -e "\033[1;31m安装 python3-devel 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
             yum install -y python3-pip 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 python3-pip 工具\033[0m" || echo -e "\033[1;31m安装 python3-pip 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
             python3 -m pip install --upgrade pip 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已更新 python3-pip 工具\033[0m" || echo -e "\033[1;31m更新 python3-pip 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
+            pip3 install setuptools 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 setuptools 模块\033[0m" || echo -e "\033[1;31m安装 setuptools 模块失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
             ;;
         *"Kali"*|*"Ubuntu"*|*"Debian"*)
             apt-get install -y python3 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 python3 工具\033[0m" || echo -e "\033[1;31m安装 python3 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
@@ -1125,7 +1125,6 @@ Pentest_pip_Install(){
     pip3 install bs4 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 bs4 模块\033[0m" || echo -e "\033[1;31m安装 bs4 模块失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
     pip3 install ftfy 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 ftfy 模块\033[0m" || echo -e "\033[1;31m安装 ftfy 模块失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
     pip3 install updog 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 updog 模块\033[0m" || echo -e "\033[1;31m安装 updog 模块失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
-
     python2 -m pip install yara 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 yara 模块\033[0m" || echo -e "\033[1;31m安装 yara 模块失败! 请尝试更换 pip 代理或检查 python2 是否已安装! \n\033[0m"
     python2 -m pip install pycrypto 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 pycrypto 模块\033[0m" || echo -e "\033[1;31m安装 pycrypto 模块失败! 请尝试更换 pip 代理或检查 python2 是否已安装! \n\033[0m"
     python2 -m pip install openpyxl 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 openpyxl 模块\033[0m" || echo -e "\033[1;31m安装 openpyxl 模块失败! 请尝试更换 pip 代理或检查 python2 是否已安装! \n\033[0m"
@@ -1661,6 +1660,7 @@ python2_Install(){
             apt-get install -y python-dev 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 python-dev 工具\033[0m" || echo -e "\033[1;31m安装 python-dev 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
             apt-get install -y python-pip 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 python2-pip 工具\033[0m" || echo -e "\033[1;31m安装 python2-pip 工具失败! 请运行 -pip2-force 选项安装 python2-pip 环境\n\033[0m"
             python2 -m pip install --upgrade pip 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已更新 python2-pip 工具\033[0m" || echo -e "\033[1;31m更新 python2-pip 工具失败(官方已停止对 pip2 更新的支持,报错可忽略)\n\033[0m"
+            python2 -m pip install setuptools 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 setuptools 模块\033[0m" || echo -e "\033[1;31m安装 setuptools 模块失败! 请尝试更换 pip 代理或检查 python2 是否已安装! \n\033[0m"
             ;;
         *) ;;
     esac
@@ -1674,6 +1674,7 @@ pip2_Install(){
     cd $T_Dir && $Porxy_OK wget https://bootstrap.pypa.io/get-pip.py 1> /dev/null 2>> /tmp/f8x_error.log || echo -e "\033[1;31m https://bootstrap.pypa.io/get-pip.py 下载失败!\n- 请检查 proxychains4 配置的代理服务器是否可用! \n\033[0m"
     $Porxy_OK python2 get-pip.py 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 python-pip 工具\033[0m" || echo -e "\033[1;31m安装 python-pip 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
     rm -rf get-pip.py 1> /dev/null 2>> /tmp/f8x_error.log
+    python2 -m pip install setuptools 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 setuptools 模块\033[0m" || echo -e "\033[1;31m安装 setuptools 模块失败! 请尝试更换 pip 代理或检查 python2 是否已安装! \n\033[0m"
 
 }
 
@@ -2047,18 +2048,21 @@ sharry_Install(){
 asciinema_Install(){
 
     echo -e "\033[1;33m\n>> 正在安装 asciinema 截图工具\n\033[0m"
-    pip3 install asciinema 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 asciinema 工具,运行以下命令开启截图:\nasciinema rec\033[0m" && exit 1 || echo -e "\033[1;31mpip3 安装 asciinema 失败,即将切换到包管理器安装\n\033[0m"
+    pip3 install asciinema 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 asciinema 工具,运行以下命令开启截图:\nasciinema rec\033[0m" || ( echo -e "\033[1;31mpip3 安装 asciinema 失败,即将切换到包管理器安装\n\033[0m" && error=1  )
 
-    Rm_Lock
-    case $Linux_Version in
-        *"CentOS"*|*"RedHat"*|*"Fedora"*)
-            yum install asciinema 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 asciinema 工具\033[0m" || echo -e "\033[1;31m安装 asciinema 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
-            ;;
-        *"Kali"*|*"Ubuntu"*|*"Debian"*)
-            apt-get install asciinema 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 asciinema 工具\033[0m" || echo -e "\033[1;31m安装 asciinema 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
-            ;;
-        *) ;;
-    esac
+    if [ $error == 1 ]
+    then
+        Rm_Lock
+        case $Linux_Version in
+            *"CentOS"*|*"RedHat"*|*"Fedora"*)
+                yum install asciinema 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 asciinema 工具\033[0m" || echo -e "\033[1;31m使用包管理器安装 asciinema 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
+                ;;
+            *"Kali"*|*"Ubuntu"*|*"Debian"*)
+                apt-get install asciinema 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;32m已安装 asciinema 工具\033[0m" || echo -e "\033[1;31m使用包管理器安装 asciinema 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
+                ;;
+            *) ;;
+        esac
+    fi
 
 }
 
@@ -2090,8 +2094,6 @@ all_Install(){
 
     Oraclejdk_Install
 
-    python2_Install
-
     nn_Install
 
     Fun_Tools
@@ -2113,6 +2115,8 @@ Dev_Tools(){
     Dev_Base_Install
     echo -e "\033[1;33m\n>> 正在安装 python3 和 pip3\n\033[0m"
     Python3_Install
+    echo -e "\033[1;33m\n>> 正在安装 python2 和 pip2\n\033[0m"
+    python2_Install
     echo -e "\033[1;33m\n>> 正在安装 Go\n\033[0m"
     Go_Install
     echo -e "\033[1;33m\n>> 正在安装 Docker 和 Docker-compose\n\033[0m"
