新增对 Typhon 和 Fenjing 工具的安装函数，并优化相关安装逻辑

diff --git a/f8x b/f8x
--- a/f8x
+++ b/f8x
@@ -861,6 +861,12 @@ Install_Switch7(){
 
 }
 
+Install_Switch8(){
+
+    pipx install $1 $1 1> /dev/null 2>> /tmp/f8x_error.log && Echo_INFOR "Successfully installed $1 (python3 pipx)" && return 0 || { Echo_ERROR "$1 module installation failed"; return 1; }
+
+}
+
 # ===================== Proxy Switch =====================
 Proxy_Switch(){
 
@@ -2571,6 +2577,8 @@ pyenv_Install(){
                     ;;
                 *) ;;
             esac
+
+            Install_Switch "pipx"
         fi
     fi
 
@@ -2584,6 +2592,7 @@ Python3_def_Install(){
         *"CentOS"*|*"RedHat"*|*"Fedora"*|*"AlmaLinux"*|*"VzLinux"*|*"Rocky"*)
             Install_Switch "python3-devel"
             Install_Switch "python3-pip"
+            Install_Switch "pipx"
             python3 -m pip install --upgrade pip > /dev/null 2>&1 && Echo_INFOR "Updated python3-pip" || Echo_ERROR "Update python3-pip failed"
 
             Install_Switch4 "setuptools"
@@ -2595,6 +2604,7 @@ Python3_def_Install(){
             Install_Switch "python3-pip"
             Install_Switch "python3-venv"
             Install_Switch "python3-distutils"
+            Install_Switch "pipx"
             python3 -m pip install --upgrade pip > /dev/null 2>&1 && Echo_INFOR "Updated python3-pip" || Echo_ERROR "Update python3-pip failed"
             ;;
         *"Ubuntu"*)
@@ -2603,6 +2613,7 @@ Python3_def_Install(){
             Install_Switch "python3-pip"
             Install_Switch "python3-venv"
             Install_Switch "python3-distutils"
+            Install_Switch "pipx"
             case $Linux_Version_Num in
                 "16.04")
                     mkdir -p /tmp/get-pip && cd /tmp/get-pip && rm -rf get-pip.py && $Proxy_OK wget https://bootstrap.pypa.io/pip/3.5/get-pip.py > /dev/null 2>&1
