v1.4.0 * 添加 -mobsf 安装选项 * 添加 -nodejsscan 安装选项 * -k 选项添加 Nuclei 工具 * 修改部署 CobaltStrike 环境的提示信息 * 优化 -h 的排列效果

diff --git a/f8x b/f8x
--- a/f8x
+++ b/f8x
@@ -25,7 +25,7 @@ Default_DNS=223.5.5.5
 Proxy_URL=https://ffffffff0x.com/proxychains-ng.zip
 Porxy_OK=
 error=0
-F8x_Version="1.3.9 Dev"
+F8x_Version="1.4.0 Dev"
 
 # ===================== 软件版本变量设置 =====================
 jdk_Version=jdk1.8.0_271
@@ -56,6 +56,8 @@ fscan_Ver=1.4
 fscan_Install=fscan_amd64
 ffuf_Ver=v1.1.0
 ffuf_Install=ffuf_1.1.0_linux_amd64.tar.gz
+Nuclei_Ver=v2.2.0
+Nuclei_Install=nuclei_2.2.0_linux_amd64.tar.gz
 
 # ===================== 基础文件夹 =====================
 Base_Dir(){
@@ -1092,6 +1094,7 @@ Pentest_Base_Install(){
 
     if test -d $P_Dir
     then
+        echo -e "\033[1;33m$(date +"%H:%M:%S")\033[0m \033[1;33m[INFOR]\033[0m - \033[1;33m文件夹存在\033[0m"
         echo -e "\033[1;33m\n>> 检测到 /pentest 文件夹已存在,是否继续? [Y/n,默认Yes] \033[0m" && read -r input
         case $input in
             [nN][oO]|[nN])
@@ -1343,7 +1346,7 @@ Pentest_CobaltStrike_Install(){
 
     if test -e $P_Dir/$CS_Version/cobaltstrike.store
     then
-        echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32mcobaltstrike.store 文件已生成\033[0m"
+        echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32mcobaltstrike.store 文件已生成,默认 keypass 为 123456,实战中强烈建议替换!!! \033[0m"
     else
         echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m运行 keytool 失败,此步骤需要 jdk 环境,请使用 -oraclejdk 选项安装 jdk 环境,然后运行以下命令\n/usr/local/java/$jdk_Version/bin/keytool -keystore $P_Dir/$CS_Version/cobaltstrike.store -storepass 123456 -keypass 123456 -genkey -keyalg RSA -alias aliyun -dname \"CN=aliyun, OU=aliyun, O=aliyun, L=aliyun, S=aliyun, C=aliyun\"\n手动生成 cobaltstrike.store 文件!\n\033[0m"
     fi
@@ -1431,6 +1434,19 @@ Pentest_fscan_Install(){
 Pentest_pocsuite3_Install(){
 
     pip3 install pocsuite3 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已安装 pocsuite3 工具,直接输入 pocsuite 即可使用\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m安装 pocsuite3 工具失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
+
+}
+
+# ===================== 安装 Nuclei 工具 =====================
+Pentest_Nuclei_Install(){
+
+    cd /tmp && rm -rf $Nuclei_Install 1> /dev/null 2>> /tmp/f8x_error.log && $Porxy_OK wget https://github.com/projectdiscovery/nuclei/releases/download/$Nuclei_Ver/$Nuclei_Install 1> /dev/null 2>> /tmp/f8x_error.log || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m$Nuclei_Install 下载失败! 请检查 proxychains4 配置的代理服务器是否可用! \n\033[0m"
+    tar -zxvf $Nuclei_Install 1> /dev/null 2>> /tmp/f8x_error.log || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m解压 /tmp/$Nuclei_Install 失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
+    mv --force nuclei /usr/local/bin/ && chmod +x /usr/local/bin/nuclei && rm -rf /tmp/$Nuclei_Install 1> /dev/null 2>> /tmp/f8x_error.log
+    nuclei -version 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已安装 Nuclei $Nuclei_Ver 在 /usr/local/bin/ 目录下,直接输入 nuclei 即可使用\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31mnuclei 安装失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
+
+    echo -e "\033[1;33m\n>> 正在更新 Nuclei 扫描规则\n\033[0m"
+    $Porxy_OK nuclei -update-templates 1> /dev/null 2>> /tmp/f8x_error.log && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已更新 nuclei-templates 列表\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31mnuclei-templates 列表更新失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
 
 }
 
@@ -1944,6 +1960,28 @@ awvs13_Install(){
 
 }
 
+# -mobsf
+mobsf_Install(){
+
+    echo -e "\033[1;33m\n>> 正在检测 Docker 可用性\n\033[0m"
+    Docker_Install
+
+    echo -e "\033[1;33m\n>> 正在部署 MobSF 环境\n\033[0m"
+    docker pull opensecurity/mobile-security-framework-mobsf && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已拉取最新版 MobSF 镜像, 请通过下列命令运行:\n$Porxy_OK docker run -it --rm -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest\n\n-browser access：http://127.0.0.1:8000/\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m部署 MobSF 环境失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
+
+}
+
+# -nodejsscan
+nodejsscan_Install(){
+
+    echo -e "\033[1;33m\n>> 正在检测 Docker 可用性\n\033[0m"
+    Docker_Install
+
+    echo -e "\033[1;33m\n>> 正在部署 nodejsscan 环境\n\033[0m"
+    docker pull opensecurity/nodejsscan:latest && echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;32m[INFOR]\033[0m - \033[1;32m已拉取最新版 nodejsscan 镜像, 请通过下列命令运行:\ndocker run -it -p 9090:9090 opensecurity/nodejsscan:latest\n\n-browser access：http://127.0.0.1:9090/\033[0m" || echo -e "\033[1;36m$(date +"%H:%M:%S")\033[0m \033[1;31m[ERROR]\033[0m - \033[1;31m部署 nodejsscan 环境失败,请查看日志 /tmp/f8x_error.log \n\033[0m"
+
+}
+
 # -viper
 viper_Install(){
 
@@ -2271,7 +2309,7 @@ all_Install(){
 
     nn_Install
 
-    Fun_Tools
+    #Fun_Tools
 
     kali_Tools
 
@@ -2360,6 +2398,8 @@ kali_Tools(){
     Pentest_fscan_Install
     echo -e "\033[1;33m\n>> 正在安装 pocsuite3 工具\n\033[0m"
     Pentest_pocsuite3_Install
+    echo -e "\033[1;33m\n>> 正在安装 Nuclei 工具\n\033[0m"
+    Pentest_Nuclei_Install
 
 }
 
@@ -2398,52 +2438,56 @@ Help(){
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-s\033[0m \033[0;34m选项加固 linux 服务器 \033[0m  \033[1;32m(Fail2Ban)\033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-f\033[0m \033[0;34m选项安装其他工具 \033[0m       \033[1;32m(Bash_Insulter、vlmcsd、AdguardTeam、trash-cli)\033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-h\033[0m \033[0;34m选项查看帮助文档 \033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-all\033[0m \033[0;34m选项全自动化部署\033[0m      \033[1;32m(默认不走代理,兼容 CentOS7/8,Debain10/9,Ubuntu20/18,Fedora33)\033[0m"
     echo -e ""
     echo -e "\033[1;33m(以下选项运行前,请先运行 -b 选项安装一遍基本环境!!!否则缺少库必报错)\033[0m"
-    echo -e "\033[1;34m开发可选项 \033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-ssh\033[0m \033[0;34m选项配置 SSH 环境 \033[0m   \033[1;33m (RedHat 系默认可用,无需重复安装)\033[0m"
+    echo -e "\033[1;34m开发环境 \033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-nn\033[0m \033[0;34m选项安装 npm & NodeJs 环境 \033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-oraclejdk\033[0m \033[0;34m选项安装 oraclejdk 环境 \033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-openjdk\033[0m \033[0;34m选项安装 openjdk 环境 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-python3\033[0m \033[0;34m选项安装 python3 环境 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-python2\033[0m \033[0;34m选项安装 python2 环境 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-pip2-force\033[0m \033[0;34m选项强制安装 pip2 环境 \033[0m  \033[1;33m(建议在 -python2 选项失败的情况下运行)\033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-perl\033[0m \033[0;34m选项安装 perl 环境 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-ruby\033[0m \033[0;34m选项安装 ruby 环境 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-rust\033[0m \033[0;34m选项安装 rust 环境 \033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-oraclejdk\033[0m \033[0;34m选项安装 oraclejdk 环境 \033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-openjdk\033[0m \033[0;34m选项安装 openjdk 环境 \033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-perl\033[0m \033[0;34m选项安装 perl 环境 \033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-nn\033[0m \033[0;34m选项安装 npm & NodeJs 环境 \033[0m"
     echo -e ""
-    echo -e "\033[1;34m安全可选项 \033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-volatility\033[0m \033[0;34m选项安装 volatility 工具 \033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-volatility3\033[0m \033[0;34m选项安装 volatility3 工具 \033[0m"
+    echo -e "\033[1;34m蓝队服务 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-binwalk\033[0m \033[0;34m选项安装 binwalk 环境 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-binwalk-force\033[0m \033[0;34m选项强制安装 binwalk 环境 \033[0m \033[0m  \033[1;33m(建议在 -binwalk 选项失败的情况下运行)\033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-vulhub\033[0m \033[0;34m选项部署 vulhub 环境 \033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-vulfocus\033[0m \033[0;34m选项部署 vulfocus 环境 \033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-volatility\033[0m \033[0;34m选项安装 volatility 工具 \033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-volatility3\033[0m \033[0;34m选项安装 volatility3 工具 \033[0m"
+    echo -e ""
+    echo -e "\033[1;34m红队服务 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-cs\033[0m \033[0;34m选项部署 CobaltStrike 环境 \033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-goby\033[0m \033[0;34m选项部署 Goby 环境 (需要图形化环境)\033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-awvs13\033[0m \033[0;34m选项部署 AWVS13 环境\033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-viper\033[0m \033[0;34m选项部署 Viper 环境 (本项不稳定)\033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-arl\033[0m \033[0;34m选项部署 ARL 环境\033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-frp\033[0m \033[0;34m选项部署 frp 环境 \033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-goby\033[0m \033[0;34m选项部署 Goby 环境 (需要图形化环境)\033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-nps\033[0m \033[0;34m选项部署 nps 环境 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-suricata\033[0m \033[0;34m选项部署 Suricata 环境 \033[0m"
     echo -e ""
-    echo -e "\033[1;34m服务可选项 \033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-sharry\033[0m \033[0;34m选项部署 sharry 文件服务 \033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-bt\033[0m \033[0;34m选项部署宝塔服务 \033[0m"
+    echo -e "\033[1;34m基于 Docker 的环境部署\033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-arl\033[0m \033[0;34m选项部署 ARL 环境\033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-awvs13\033[0m \033[0;34m选项部署 AWVS13 环境\033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-mobsf\033[0m \033[0;34m选项部署 MobSF 环境 \033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-nodejsscan\033[0m \033[0;34m选项部署 nodejsscan 环境\033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-viper\033[0m \033[0;34m选项部署 Viper 环境 (本项不稳定)\033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-vulhub\033[0m \033[0;34m选项部署 vulhub 环境 \033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-vulfocus\033[0m \033[0;34m选项部署 vulfocus 环境 \033[0m"
     echo -e ""
-    echo -e "\033[1;34m其他可选项 \033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-ssr\033[0m \033[0;34m选项部署 ssr 工具 \033[0m"
+    echo -e "\033[1;34m杂项服务 \033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-asciinema\033[0m \033[0;34m选项安装 asciinema 截图工具 \033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-bt\033[0m \033[0;34m选项部署宝塔服务 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-music\033[0m \033[0;34m选项部署 UnblockNeteaseMusic 服务 \033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-optimize\033[0m \033[0;34m选项改善设备选项,优化性能 \033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-info\033[0m \033[0;34m选项查看系统各项信息 \033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-sharry\033[0m \033[0;34m选项部署 sharry 文件服务 \033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-ssh\033[0m \033[0;34m选项配置 SSH 环境 \033[0m   \033[1;33m (RedHat 系默认可用,无需重复安装)\033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-ssr\033[0m \033[0;34m选项部署 ssr 工具 \033[0m"
+    echo -e ""
+    echo -e "\033[1;34m其他 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-clear\033[0m \033[0;34m选项清理系统使用痕迹 \033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-info\033[0m \033[0;34m选项查看系统各项信息 \033[0m"
+    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-optimize\033[0m \033[0;34m选项改善设备选项,优化性能 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-remove\033[0m \033[0;34m选项卸载国内vps云监控 \033[0m"
     echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-rmlock\033[0m \033[0;34m选项运行除锁模块 \033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-asciinema\033[0m \033[0;34m选项安装 asciinema 截图工具 \033[0m"
-    echo -e ""
-    echo -e "\033[1;34m一把梭,就是干 \033[0m"
-    echo -e "\033[0;34m|- 使用\033[0m \033[1;34m-all\033[0m \033[0;34m选项全自动化部署 (默认不走代理,兼容 CentOS7/8,Debain10/9,Ubuntu20/18,Fedora33)\033[0m"
     echo -e ""
     echo -e "\033[1;37m脚本作者 r0fus0d \033[0m"
     echo -e "\033[1;37m|- 感谢 the-fog 在开发过程中对我的折磨 \033[0m"
@@ -2489,37 +2533,52 @@ echo -e "\033[1;33m\n>> 正在初始化\n\033[0m"
 Base_Dir
 
 case "$1" in
-    -p)
-        Proxy
-        ;;
-    -h)
-        clear
-        Help
-        ;;
-    -b)
+    -b | b)
         Base_Install
         ;;
-    -d)
+    -p | p)
+        Proxy
+        ;;
+    -d | d)
         Base_Check
         Porxy_Switch
         Dev_Tools
         ;;
-    -k)
+    -k | k)
         Base_Check
         Dev_Check
         Porxy_Switch
         kali_Tools
         ;;
-    -f)
+    -s | s)
+        Secure
+        ;;
+    -f | f)
         Base_Check
         Porxy_Switch
         Fun_Tools
         ;;
-    -s)
-        Secure
+    -h | h)
+        clear
+        Help
         ;;
-    -ssh)
-        SSH
+    -all)
+        all_Install
+        ;;
+    -nn)
+        Base_Check
+        Porxy_Switch
+        nn_Install
+        ;;
+    -openjdk)
+        Base_Check
+        Porxy_Switch
+        Openjdk_Install
+        ;;
+    -oraclejdk)
+        Base_Check
+        Porxy_Switch
+        Oraclejdk_Install
         ;;
     -python3)
         Python3_Install
@@ -2532,6 +2591,11 @@ case "$1" in
         Porxy_Switch
         pip2_Install
         ;;
+    -perl)
+        Base_Check
+        Porxy_Switch
+        Perl_Install
+        ;;
     -ruby)
         Base_Check
         Porxy_Switch
@@ -2541,26 +2605,6 @@ case "$1" in
         Base_Check
         Porxy_Switch
         Rust_Install
-        ;;
-    -openjdk)
-        Base_Check
-        Porxy_Switch
-        Openjdk_Install
-        ;;
-    -oraclejdk)
-        Base_Check
-        Porxy_Switch
-        Oraclejdk_Install
-        ;;
-    -perl)
-        Base_Check
-        Porxy_Switch
-        Perl_Install
-        ;;
-    -nn)
-        Base_Check
-        Porxy_Switch
-        nn_Install
         ;;
     -binwalk)
         Base_Check
@@ -2584,41 +2628,20 @@ case "$1" in
         pip3_Check
         volatility3_Install
         ;;
-    -vulhub)
-        Porxy_Switch
-        vulhub_Install
-        ;;
-    -vulfocus)
-        Porxy_Switch
-        vulfocus_Install
-        ;;
     -cs)
         Base_Check
         Porxy_Switch
         cs_Install
         ;;
-    -goby)
-        Base_Check
-        Porxy_Switch
-        Goby_Install
-        ;;
-    -awvs13)
-        Porxy_Switch
-        awvs13_Install
-        ;;
-    -viper)
-        Porxy_Switch
-        viper_Install
-        ;;
-    -arl)
-        Pentest_Base_Install
-        Porxy_Switch
-        arl_Install
-        ;;
     -frp)
         Base_Check
         Porxy_Switch
         frp_Install
+        ;;
+    -goby)
+        Base_Check
+        Porxy_Switch
+        Goby_Install
         ;;
     -nps)
         Base_Check
@@ -2630,35 +2653,34 @@ case "$1" in
         Porxy_Switch
         suricata_Install
         ;;
-    -ssr)
-        Base_Check
-        ssr_Install
-        ;;
-    -music)
-        Base_Check
+    -arl)
+        Pentest_Base_Install
         Porxy_Switch
-        music_Install
+        arl_Install
         ;;
-    -optimize)
-        optimize_setting
-        ;;
-    -info)
-        Base_Check
-        System_info
-        ;;
-    -clear)
-        clear_log
-        ;;
-    -remove)
-        remove_watcher
-        ;;
-    -rmlock)
-        Rm_Lock
-        ;;
-    -sharry)
-        Base_Check
+    -awvs13)
         Porxy_Switch
-        sharry_Install
+        awvs13_Install
+        ;;
+    -mobsf)
+        Porxy_Switch
+        mobsf_Install
+        ;;
+    -nodejsscan)
+        Porxy_Switch
+        nodejsscan_Install
+        ;;
+    -viper)
+        Porxy_Switch
+        viper_Install
+        ;;
+    -vulhub)
+        Porxy_Switch
+        vulhub_Install
+        ;;
+    -vulfocus)
+        Porxy_Switch
+        vulfocus_Install
         ;;
     -asciinema)
         asciinema_Install
@@ -2667,8 +2689,38 @@ case "$1" in
         Base_Check
         bt_Install
         ;;
-    -all)
-        all_Install
+    -music)
+        Base_Check
+        Porxy_Switch
+        music_Install
+        ;;
+    -sharry)
+        Base_Check
+        Porxy_Switch
+        sharry_Install
+        ;;
+    -ssh)
+        SSH
+        ;;
+    -ssr)
+        Base_Check
+        ssr_Install
+        ;;
+    -clear)
+        clear_log
+        ;;
+    -info)
+        Base_Check
+        System_info
+        ;;
+    -optimize)
+        optimize_setting
+        ;;
+    -remove)
+        remove_watcher
+        ;;
+    -rmlock)
+        Rm_Lock
         ;;
     -debug)
         Base_Check
